# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cintent.proto\x12\x06intent\"\x1d\n\rIntentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0eIntentResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2J\n\rIntentService\x12\x39\n\x06Result\x12\x15.intent.IntentRequest\x1a\x16.intent.IntentResponse\"\x00\x62\x06proto3')



_INTENTREQUEST = DESCRIPTOR.message_types_by_name['IntentRequest']
_INTENTRESPONSE = DESCRIPTOR.message_types_by_name['IntentResponse']
IntentRequest = _reflection.GeneratedProtocolMessageType('IntentRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTENTREQUEST,
  '__module__' : 'intent_pb2'
  # @@protoc_insertion_point(class_scope:intent.IntentRequest)
  })
_sym_db.RegisterMessage(IntentRequest)

IntentResponse = _reflection.GeneratedProtocolMessageType('IntentResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTENTRESPONSE,
  '__module__' : 'intent_pb2'
  # @@protoc_insertion_point(class_scope:intent.IntentResponse)
  })
_sym_db.RegisterMessage(IntentResponse)

_INTENTSERVICE = DESCRIPTOR.services_by_name['IntentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTENTREQUEST._serialized_start=24
  _INTENTREQUEST._serialized_end=53
  _INTENTRESPONSE._serialized_start=55
  _INTENTRESPONSE._serialized_end=87
  _INTENTSERVICE._serialized_start=89
  _INTENTSERVICE._serialized_end=163
# @@protoc_insertion_point(module_scope)
